# Generated by Django 4.1.7 on 2023-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rateing',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
