# Generated by Django 4.1.7 on 2023-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_movie_rateing'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=5, upload_to=''),
            preserve_default=False,
        ),
    ]
